install.packages("moments")
install.packages("ROCR")
install.packages("dotwhisker")
library(moments)
library(rpart)
library(rpart.plot)
library(caret)
library(caTools)
library(dplyr)
library(ggplot2)
library(GGally)
library(ROCR)
library(dotwhisker)
l = read.csv("loanset.csv")

loan = data.frame(l)
View(loan)
str(loan)
nrow(loan)
ncol(loan)

loan = subset(loan, select=-c(customer.id,credit.policy))
loan$purpose = as.factor(loan$purpose)
loan$purpose = as.integer(loan$purpose)
loan$dti = as.numeric(loan$dti)
loan$revol.util = as.numeric(loan$revol.util)
loan$delinq.2yrs = as.numeric(loan$delinq.2yrs)
loan$pub.rec = as.numeric(loan$pub.rec)
str(loan)
View(loan)
loan = na.omit(loan)
View(loan)
str(loan)
ggcorr(loan)
loan %>% summarise_if(is.numeric, mean)
loan %>% summarise_if(is.numeric, sd)
loan %>% summarise_if(is.numeric, min)
loan %>% summarise_if(is.numeric, max)
loan %>% summarise_if(is.numeric, median)
loan %>% ggplot(aes(x = not.fully.paid)) + geom_bar()
table(skewness(loan))
duplicated(loan)
table(loan$not.fully.paid)

start.model = glm(not.fully.paid ~ ., data = loan, family = "binomial")
summary(start.model)
str(loan)

set.seed(2001)
distribution = sample.split(loan$not.fully.paid, SplitRatio = 0.7)
train = subset(loan, distribution == TRUE)
test = subset(loan, distribution == FALSE)
View(train)
nrow(train)
nrow(test)

plot(loan$fico, loan$not.fully.paid)
plot(loan$installment, loan$not.fully.paid)
plot(loan$log.annual.inc, loan$not.fully.paid)
plot(loan$revol.bal, loan$not.fully.paid)
plot(loan$inq.last.6mths, loan$not.fully.paid)
plot(loan$pub.rec, loan$not.fully.paid)


first.model = glm(not.fully.paid ~ ., data = train, family = "binomial")
summary(first.model)
real.model = glm(not.fully.paid ~ installment + fico + 
                   log.annual.inc + revol.bal + inq.last.6mths, data = train, family = "binomial")
dwplot(real.model)
summary(real.model)
predictor = predict(real.model, newdata = test, type = "response")
predict(real.model, newdata = fake.data, type = "response")
table(test$not.fully.paid, predictor > 0.7)
(2397)/nrow(test)
#84%
table(test$not.fully.paid, predictor > 0.4)
(2383+17)/nrow(test)
#84% accuracy
table(test$not.fully.paid, predictor > 0.1)
(505+434)/nrow(test)
#32% accuracy lmao

barplot(table(loan$not.fully.paid), names.arg=c('paid','not paid'), 
        main='Distribution of loan payment', xlab='payment completion', ylab='Count')


#source - https://rviews.rstudio.com/2019/03/01/some-r-packages-for-roc-curves/
roc.prediction = prediction(predictor, test$not.fully.paid)
roc.performance = performance(roc.curve, "tpr", "fpr") 
plot(roc.performance, colorize = TRUE)
